databases:
  - name: dlf-africa-db
    databaseName: dlf-africa
    user: dlf-user

services:
  - type: web
    name: dlf-africa-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: dlf-africa-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000