databases:
  - name: dlf-africa-db
    databaseName: dlf-africa
    user: dlf-user

services:
  - type: web
    name: dlf-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: dlf-africa-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000